# Generated by Django 5.2.5 on 2026-05-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FireScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="场景标题")),
                (
                    "topic",
                    models.CharField(
                        help_text="例如: 电气火灾、违规动火等", max_length=100, verbose_name="主题分类"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("low", "低难度"), ("medium", "中难度"), ("high", "高难度")],
                        default="medium",
                        max_length=20,
                        verbose_name="难度",
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="用于向用户播报和展示的现场情况", verbose_name="场景描述"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="scenarios/",
                        verbose_name="现场模拟图",
                    ),
                ),
                (
                    "correct_actions",
                    models.TextField(
                        help_text="供 Agent 评估用户回答的参考标准", verbose_name="标准处置流程"
                    ),
                ),
                (
                    "analysis",
                    models.TextField(
                        help_text="演练结束后给出的整体点评和原因分析", verbose_name="案例分析总结"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "消防演练场景",
                "verbose_name_plural": "消防演练场景",
                "db_table": "scenario_training_case",
            },
        ),
    ]
