# Generated by Django 5.2.5 on 2026-05-06 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="training_materials/", verbose_name="原始文档"
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                ("file_type", models.CharField(max_length=20, verbose_name="文件类型")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待处理"),
                            ("processing", "解析中"),
                            ("completed", "已完成"),
                            ("failed", "解析失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "raw_analysis",
                    models.JSONField(blank=True, null=True, verbose_name="大模型原始解析结果"),
                ),
                (
                    "result_teaching",
                    models.TextField(blank=True, null=True, verbose_name="生成的教学内容"),
                ),
                (
                    "result_scenarios",
                    models.JSONField(blank=True, null=True, verbose_name="生成的场景题目"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "培训素材管理",
                "verbose_name_plural": "培训素材管理",
                "db_table": "scenario_training_material",
            },
        ),
        migrations.AddField(
            model_name="firescenario",
            name="teaching_content",
            field=models.TextField(
                blank=True, help_text="数字人先播报的教学内容", null=True, verbose_name="教学讲义内容"
            ),
        ),
        migrations.AlterField(
            model_name="firescenario",
            name="description",
            field=models.TextField(help_text="用于向用户播报和展示的现场情况", verbose_name="演练场景描述"),
        ),
        migrations.AddField(
            model_name="firescenario",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scenarios",
                to="scenarios.trainingmaterial",
                verbose_name="所属素材",
            ),
        ),
    ]
