# Generated by Django 5.2.13 on 2026-05-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkillPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=32)),
                (
                    "skill",
                    models.CharField(
                        choices=[
                            ("knowledge_qa", "基础知识库问答"),
                            ("report_gen", "报告生成"),
                            ("hazard_detect", "隐患识别"),
                            ("analytics", "数据分析"),
                        ],
                        max_length=32,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Skill 权限",
                "verbose_name_plural": "Skill 权限",
                "unique_together": {("role", "skill")},
            },
        ),
    ]
