# Generated by Django 5.2.13 on 2026-05-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "source",
                    models.CharField(
                        help_text="用于在向量库中删除该文档相关的全部 chunk",
                        max_length=200,
                        unique=True,
                        verbose_name="来源标识",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="描述"
                    ),
                ),
                ("chunk_count", models.IntegerField(default=0, verbose_name="片段数")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="knowledge_base/",
                        verbose_name="原始文件",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "知识库文档",
                "verbose_name_plural": "知识库文档",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="QASession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="问题")),
                ("answer", models.TextField(verbose_name="回答")),
                ("sources", models.JSONField(default=list, verbose_name="引用片段")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "问答记录",
                "verbose_name_plural": "问答记录",
                "ordering": ("-created_at",),
            },
        ),
    ]
