# Generated by Django 5.2.13 on 2026-05-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HazardDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lab_name",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="实验室"
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(
                        upload_to="hazards/original/", verbose_name="原始图片"
                    ),
                ),
                (
                    "annotated_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="hazards/annotated/",
                        verbose_name="标注图片",
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, default="", verbose_name="整体评估"),
                ),
                (
                    "overall_severity",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        default="medium",
                        max_length=10,
                        verbose_name="总体风险",
                    ),
                ),
                (
                    "hazards",
                    models.JSONField(
                        default=list,
                        help_text="[{name, category, severity, description, suggestion, bbox}]",
                        verbose_name="隐患明细",
                    ),
                ),
                ("image_width", models.IntegerField(default=0, verbose_name="图片宽")),
                ("image_height", models.IntegerField(default=0, verbose_name="图片高")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "隐患识别",
                "verbose_name_plural": "隐患识别",
                "ordering": ("-created_at",),
            },
        ),
    ]
