# Generated by Django 6.0.4 on 2026-05-03 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hazards", "0002_initial"),
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hazarddetection",
            name="lab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hazard_detections",
                to="labs.lab",
                verbose_name="实验室",
            ),
        ),
        migrations.AddField(
            model_name="hazarddetection",
            name="other_location",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="其他地点"
            ),
        ),
    ]
