# Generated by Django 6.0.4 on 2026-05-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0003_hazarddetection_lab_hazarddetection_other_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazarddetection',
            name='media_type',
            field=models.CharField(choices=[('image', '图片'), ('video', '视频')], default='image', max_length=10, verbose_name='媒体类型'),
        ),
        migrations.AlterField(
            model_name='hazarddetection',
            name='original_image',
            field=models.FileField(upload_to='hazards/original/', verbose_name='原始媒体'),
        ),
    ]
