# Generated by Django 6.0.4 on 2026-05-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0004_hazarddetection_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazarddetection',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='hazards/covers/', verbose_name='封面图'),
        ),
    ]
