# Generated by Django 6.0.4 on 2026-05-03 19:14

from django.db import migrations


def migrate_lab_names(apps, schema_editor):
    Lab = apps.get_model('labs', 'Lab')
    HazardDetection = apps.get_model('hazards', 'HazardDetection')
    Report = apps.get_model('reports', 'Report')
    User = apps.get_model('users', 'User')

    # Collect all non-empty lab_name values
    names = set()
    for model in (HazardDetection, Report, User):
        for val in model.objects.exclude(lab_name='').values_list('lab_name', flat=True).distinct():
            if val:
                names.add(val.strip())

    # Create Lab records
    lab_map = {}
    for name in names:
        lab, _ = Lab.objects.get_or_create(name=name, defaults={'address': ''})
        lab_map[name] = lab

    # Link existing records to Lab
    for model in (HazardDetection, Report, User):
        for instance in model.objects.exclude(lab_name=''):
            lab = lab_map.get(instance.lab_name.strip())
            if lab:
                instance.lab_id = lab.id
                instance.save(update_fields=['lab_id'])


def reverse_migrate(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('labs', '0001_initial'),
        ('hazards', '0003_hazarddetection_lab_hazarddetection_other_location'),
        ('reports', '0004_report_lab_report_other_location'),
        ('users', '0002_user_lab_user_other_location'),
    ]

    operations = [
        migrations.RunPython(migrate_lab_names, reverse_migrate),
    ]
