# Generated by Django 6.0.4 on 2026-05-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0002_auto_20260504_0314"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lab",
            name="address",
        ),
    ]
