# Generated by Django 5.2.13 on 2026-05-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="报告标题")),
                (
                    "lab_name",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="实验室名称"
                    ),
                ),
                (
                    "inspector",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="检查人"
                    ),
                ),
                (
                    "summary_stats",
                    models.JSONField(
                        default=dict,
                        help_text="{total, by_severity, by_category}",
                        verbose_name="汇总统计",
                    ),
                ),
                (
                    "agent_evaluation",
                    models.TextField(blank=True, default="", verbose_name="agent 评价"),
                ),
                (
                    "references",
                    models.JSONField(
                        default=list,
                        help_text="[{title, snippet}]",
                        verbose_name="参考依据",
                    ),
                ),
                (
                    "extra_notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/pdf/",
                        verbose_name="PDF",
                    ),
                ),
                (
                    "docx_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/docx/",
                        verbose_name="DOCX",
                    ),
                ),
                (
                    "overall_severity",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        default="medium",
                        max_length=10,
                        verbose_name="总体风险",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "报告",
                "verbose_name_plural": "报告",
                "ordering": ("-created_at",),
            },
        ),
    ]
