# Generated by Django 5.2.13 on 2026-05-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="address",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="检查地址"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="lab_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=128,
                verbose_name="实验室名称",
            ),
        ),
    ]
